<?php

/**
 * @file
 * Quiz_directions question type for the Quiz module.
 *
 * Directions are implemented as a question type. However, they do not affect
 * the score.
 */


/**
 * Implements hook_autolosd_info().
 */
function quiz_directions_autoload_info() {
  return array(
    'QuizDirectionsQuestion' => 'includes/QuizDirectionsQuestion.class.inc',
    'QuizDirectionsResponse' => 'includes/QuizDirectionsResponse.class.inc',
    'QuizDirectionsTestCase' => 'tests/QuizDirectionsTestCase.inc',
  );
}

/**
 * Implements hook_quiz_question_info().
 */
function quiz_directions_quiz_question_info() {
  return array(
    'quiz_directions' => array(
      'name' => t('@quiz directions', array('@quiz' => QUIZ_NAME)),
      'description' => t('@quiz directions allow you to drop in directions anywhere in a quiz. You can also use them to insert a confirmation step at the end of the quiz.', array('@quiz' => QUIZ_NAME)),
      'question provider' => 'QuizDirectionsQuestion',
      'response provider' => 'QuizDirectionsResponse',
      // All wrapper functions are in the quiz_question module.
      'module' => 'quiz_question',
    ),
  );
}

/**
 * Implements hook_quiz_question_config().
 */
function quiz_directions_quiz_question_config() {
  return FALSE;
}

/**
 * Implements hook_theme().
 */
function quiz_directions_theme() {
  return array(
    'quiz_directions_answering_form' => array(
      'render element' => 'form',
      'path' => backdrop_get_path('module', 'quiz_directions') . '/theme',
      'template' => 'quiz-directions-answering-form',
    ),
  );
}
