<?php

/**
 * @file
 * Quiz_page question type for the Quiz module.
 *
 * Pages are implemented as a question type. However, they do not affect the
 * score.
 */

/**
 * Implements hook_autoload_info*().
 *
 * @return string[]
 */
function quiz_page_autoload_info() {
  return array(
    'QuizPageQuestion' => 'includes/QuizPageQuestion.class.inc',
    'QuizPageResponse' => 'includes/QuizPageResponse.class.inc',
    'QuizPageTestCase' => 'tests/QuizPageTestCase.test',
  );
}

/**
 * Implements hook_config_info().
 */
function quiz_page_config_info() {
  $prefixes['quiz_page.settings'] = array(
    'label' => t('Quiz Page settings'),
    'group' => t('Quiz Page'),
  );
  return $prefixes;
}

/**
 * Implements hook_quiz_question_info().
 */
function quiz_page_quiz_question_info() {
  return array(
    'quiz_page' => array(
      'name' => t('@quiz page', array('@quiz' => QUIZ_NAME)),
      'description' => t('Quiz pages allow you display questions across multiple pages.'),
      'question provider' => 'QuizPagesQuestion',
      'response provider' => 'QuizPagesResponse',
      // All wrapper functions are in the quiz_question module.
      'module' => 'quiz_question',
    ),
  );
}

/**
 * Implements hook_quiz_question_config().
 */
function quiz_page_quiz_question_config() {
  return FALSE;
}
